---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    k8s-app: nginx
spec:
  containers:
  - name: nginx
    image: n1654/3-tier-app-nginx:0.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-config
    configMap:
      name: cmap-nginx
