apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: msa-db
  name: msa-db
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      type: nfs
