apiVersion: v1
kind: PersistentVolume
metadata:
  name: msa-svn
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.31.1.232
    path: /export/msa-svn
