apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: msa-front
  name: msa-front
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "514"
      port: 514
      protocol: UDP
      targetPort: 514
    - name: "162"
      port: 162
      protocol: UDP
      targetPort: 162
    - name: "69"
      port: 69
      protocol: UDP
      targetPort: 69
    - name: "5200"
      port: 5200
      protocol: UDP
      targetPort: 5200
  selector:
    io.kompose.service: msa-front
status:
  loadBalancer: {}
